services:
  db:
    image: postgres:17-alpine
    container_name: fitness_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitness_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../DB/fitness_backup.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fitness_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

